version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env.dev
    ports:
      - '5430:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data # Persistent storage

  redis:
    image: redis:7.2
    container_name: redis_container
    restart: always
    ports:
      - '6380:6379' # Expose Redis for BullMQ
    command: redis-server --save 60 1 --loglevel warning #save data to disk every 60 seconds if at least 1 change is made.
    volumes:
      - redisdata:/data # Persistent storage for Redis


  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env.dev

volumes:
  pgdata:
  redisdata: # Add Redis storage

